/** 业务模块元数据：列、动作、状态与页面文案集中登记，各明细页共用。 */
export interface ModuleMeta {
  key: string
  title: string
  desc: string
  fields: string[]
  actions: string[]
  statuses: string[]
  primaryText: string
  exportText: string
  emptyText: string
  recordNoun: string
  createHint: string
  actionFail: string
  listThrow: string
  listFail: string
}

export const MODULES: ModuleMeta[] = [
  {
  key: "register",
  title: "使用登记管理",
  desc: "维护设备登记，围绕设备编号、设备名称、设备种类、使用单位做登记、筛选与状态流转。",
  fields: ["设备编号", "设备名称", "设备种类", "使用单位", "安装地点", "投用日期", "登记证号", "登记状态"],
  actions: ["办理登记", "申请停用", "申请注销"],
  statuses: ["待登记", "已登记", "停用中", "已注销"],
  primaryText: "登记设备登记",
  exportText: "导出使用登记清单",
  emptyText: "暂无使用登记数据，可先登记设备登记",
  recordNoun: "使用登记记录",
  createHint: "设备登记登记入口尚未接入审批流",
  actionFail: "使用登记动作未生效，请稍后重试",
  listThrow: "设备登记列表读取失败",
  listFail: "使用登记操作失败"
  },
  {
  key: "boiler",
  title: "锅炉管理管理",
  desc: "维护锅炉，围绕锅炉编号、锅炉型号、额定蒸发量、工作压力做登记、筛选与状态流转。",
  fields: ["锅炉编号", "锅炉型号", "额定蒸发量", "工作压力", "燃料类型", "使用年限", "司炉人员", "锅炉状态"],
  actions: ["降负荷运行", "停炉检修", "恢复运行"],
  statuses: ["正常运行", "低负荷", "检修中", "已停炉"],
  primaryText: "登记锅炉",
  exportText: "导出锅炉管理清单",
  emptyText: "暂无锅炉管理数据，可先登记锅炉",
  recordNoun: "锅炉管理记录",
  createHint: "锅炉登记入口尚未接入审批流",
  actionFail: "锅炉管理动作未生效，请稍后重试",
  listThrow: "锅炉列表读取失败",
  listFail: "锅炉管理操作失败"
  },
  {
  key: "pressurevessel",
  title: "压力容器管理",
  desc: "维护压力容器，围绕容器编号、容器类别、设计压力、工作温度做登记、筛选与状态流转。",
  fields: ["容器编号", "容器类别", "设计压力", "工作温度", "介质名称", "容积", "安全附件", "容器状态"],
  actions: ["降压运行", "安排检验", "办理停用"],
  statuses: ["正常", "超压运行", "检验中", "已停用"],
  primaryText: "登记压力容器",
  exportText: "导出压力容器清单",
  emptyText: "暂无压力容器数据，可先登记压力容器",
  recordNoun: "压力容器记录",
  createHint: "压力容器登记入口尚未接入审批流",
  actionFail: "压力容器动作未生效，请稍后重试",
  listThrow: "压力容器列表读取失败",
  listFail: "压力容器操作失败"
  },
  {
  key: "pipeline",
  title: "压力管道管理",
  desc: "维护压力管道，围绕管道编号、管道级别、设计压力、输送介质做登记、筛选与状态流转。",
  fields: ["管道编号", "管道级别", "设计压力", "输送介质", "管道长度", "敷设方式", "检验日期", "管道状态"],
  actions: ["记录减薄", "安排检验", "申请报废"],
  statuses: ["正常", "壁厚减薄", "待检验", "已报废"],
  primaryText: "登记压力管道",
  exportText: "导出压力管道清单",
  emptyText: "暂无压力管道数据，可先登记压力管道",
  recordNoun: "压力管道记录",
  createHint: "压力管道登记入口尚未接入审批流",
  actionFail: "压力管道动作未生效，请稍后重试",
  listThrow: "压力管道列表读取失败",
  listFail: "压力管道操作失败"
  },
  {
  key: "elevator",
  title: "电梯管理管理",
  desc: "维护电梯，围绕电梯编号、电梯类型、额定载重、层站数做登记、筛选与状态流转。",
  fields: ["电梯编号", "电梯类型", "额定载重", "层站数", "维保单位", "上次维保", "下次维保日", "电梯状态"],
  actions: ["安排维保", "困人救援", "故障检修"],
  statuses: ["正常运行", "维保中", "困人", "检修中"],
  primaryText: "登记电梯",
  exportText: "导出电梯管理清单",
  emptyText: "暂无电梯管理数据，可先登记电梯",
  recordNoun: "电梯管理记录",
  createHint: "电梯登记入口尚未接入审批流",
  actionFail: "电梯管理动作未生效，请稍后重试",
  listThrow: "电梯列表读取失败",
  listFail: "电梯管理操作失败"
  },
  {
  key: "crane",
  title: "起重机械管理",
  desc: "维护起重机，围绕起重机编号、起重机类型、额定起重量、跨度做登记、筛选与状态流转。",
  fields: ["起重机编号", "起重机类型", "额定起重量", "跨度", "工作级别", "操作人员", "上次年检", "起重机状态"],
  actions: ["降载运行", "安排检验", "办理停用"],
  statuses: ["正常", "超载运行", "检验中", "已停用"],
  primaryText: "登记起重机",
  exportText: "导出起重机械清单",
  emptyText: "暂无起重机械数据，可先登记起重机",
  recordNoun: "起重机械记录",
  createHint: "起重机登记入口尚未接入审批流",
  actionFail: "起重机械动作未生效，请稍后重试",
  listThrow: "起重机列表读取失败",
  listFail: "起重机械操作失败"
  },
  {
  key: "forklift",
  title: "场车管理管理",
  desc: "维护场内车辆，围绕车辆编号、车辆类型、动力类型、核定载重做登记、筛选与状态流转。",
  fields: ["车辆编号", "车辆类型", "动力类型", "核定载重", "行驶区域", "驾驶员", "年检日期", "车辆状态"],
  actions: ["安排维修", "安排年检", "申请报废"],
  statuses: ["正常", "维修中", "待年检", "已报废"],
  primaryText: "登记场内车辆",
  exportText: "导出场车管理清单",
  emptyText: "暂无场车管理数据，可先登记场内车辆",
  recordNoun: "场车管理记录",
  createHint: "场内车辆登记入口尚未接入审批流",
  actionFail: "场车管理动作未生效，请稍后重试",
  listThrow: "场内车辆列表读取失败",
  listFail: "场车管理操作失败"
  },
  {
  key: "inspection",
  title: "定期检验管理",
  desc: "维护检验任务，围绕检验编号、被检设备、检验类别、检验机构做登记、筛选与状态流转。",
  fields: ["检验编号", "被检设备", "检验类别", "检验机构", "计划检验日", "实际检验日", "检验结论", "检验状态"],
  actions: ["安排检验", "录入结论", "下达整改"],
  statuses: ["待检验", "检验中", "合格", "不合格"],
  primaryText: "登记检验任务",
  exportText: "导出定期检验清单",
  emptyText: "暂无定期检验数据，可先登记检验任务",
  recordNoun: "定期检验记录",
  createHint: "检验任务登记入口尚未接入审批流",
  actionFail: "定期检验动作未生效，请稍后重试",
  listThrow: "检验任务列表读取失败",
  listFail: "定期检验操作失败"
  },
  {
  key: "maintenance",
  title: "维保记录管理",
  desc: "维护维保记录，围绕维保编号、维保设备、维保单位、维保内容做登记、筛选与状态流转。",
  fields: ["维保编号", "维保设备", "维保单位", "维保内容", "维保日期", "维保人员", "更换部件", "维保状态"],
  actions: ["安排维保", "开始维保", "返工登记"],
  statuses: ["待维保", "维保中", "已完成", "需返工"],
  primaryText: "登记维保记录",
  exportText: "导出维保记录清单",
  emptyText: "暂无维保记录数据，可先登记维保记录",
  recordNoun: "维保记录记录",
  createHint: "维保记录登记入口尚未接入审批流",
  actionFail: "维保记录动作未生效，请稍后重试",
  listThrow: "维保记录列表读取失败",
  listFail: "维保记录操作失败"
  },
  {
  key: "hazard",
  title: "隐患排查管理",
  desc: "维护隐患记录，围绕隐患编号、所在设备、隐患类别、隐患等级做登记、筛选与状态流转。",
  fields: ["隐患编号", "所在设备", "隐患类别", "隐患等级", "发现日期", "整改措施", "整改期限", "隐患状态"],
  actions: ["安排整改", "开始整改", "验收消除"],
  statuses: ["待整改", "整改中", "待验收", "已消除"],
  primaryText: "登记隐患记录",
  exportText: "导出隐患排查清单",
  emptyText: "暂无隐患排查数据，可先登记隐患记录",
  recordNoun: "隐患排查记录",
  createHint: "隐患记录登记入口尚未接入审批流",
  actionFail: "隐患排查动作未生效，请稍后重试",
  listThrow: "隐患记录列表读取失败",
  listFail: "隐患排查操作失败"
  },
  {
  key: "accident",
  title: "事故管理管理",
  desc: "维护事故记录，围绕事故编号、事故设备、事故类型、伤亡情况做登记、筛选与状态流转。",
  fields: ["事故编号", "事故设备", "事故类型", "伤亡情况", "直接损失", "发生时间", "调查结论", "事故状态"],
  actions: ["上报事故", "开展调查", "结案归档"],
  statuses: ["待上报", "已上报", "调查中", "已结案"],
  primaryText: "登记事故记录",
  exportText: "导出事故管理清单",
  emptyText: "暂无事故管理数据，可先登记事故记录",
  recordNoun: "事故管理记录",
  createHint: "事故记录登记入口尚未接入审批流",
  actionFail: "事故管理动作未生效，请稍后重试",
  listThrow: "事故记录列表读取失败",
  listFail: "事故管理操作失败"
  },
  {
  key: "operator",
  title: "作业人员管理",
  desc: "维护作业人员，围绕人员编号、姓名、证书类别、证书编号做登记、筛选与状态流转。",
  fields: ["人员编号", "姓名", "证书类别", "证书编号", "发证日期", "复审日期", "所属单位", "证书状态"],
  actions: ["安排复审", "登记过期", "注销证书"],
  statuses: ["持证有效", "即将到期", "已过期", "已注销"],
  primaryText: "登记作业人员",
  exportText: "导出作业人员清单",
  emptyText: "暂无作业人员数据，可先登记作业人员",
  recordNoun: "作业人员记录",
  createHint: "作业人员登记入口尚未接入审批流",
  actionFail: "作业人员动作未生效，请稍后重试",
  listThrow: "作业人员列表读取失败",
  listFail: "作业人员操作失败"
  },
  {
  key: "training",
  title: "培训考核管理",
  desc: "维护培训记录，围绕培训编号、培训内容、培训对象、培训日期做登记、筛选与状态流转。",
  fields: ["培训编号", "培训内容", "培训对象", "培训日期", "培训讲师", "考核方式", "考核结果", "培训状态"],
  actions: ["组织培训", "组织考核", "归档"],
  statuses: ["待培训", "培训中", "已考核", "已归档"],
  primaryText: "登记培训记录",
  exportText: "导出培训考核清单",
  emptyText: "暂无培训考核数据，可先登记培训记录",
  recordNoun: "培训考核记录",
  createHint: "培训记录登记入口尚未接入审批流",
  actionFail: "培训考核动作未生效，请稍后重试",
  listThrow: "培训记录列表读取失败",
  listFail: "培训考核操作失败"
  },
  {
  key: "safetyvalve",
  title: "安全阀校验管理",
  desc: "维护安全阀，围绕安全阀编号、所属设备、公称通径、整定压力做登记、筛选与状态流转。",
  fields: ["安全阀编号", "所属设备", "公称通径", "整定压力", "校验日期", "下次校验日", "校验结论", "安全阀状态"],
  actions: ["安排校验", "登记合格", "申请报废"],
  statuses: ["校验合格", "即将到期", "待校验", "已报废"],
  primaryText: "登记安全阀",
  exportText: "导出安全阀校验清单",
  emptyText: "暂无安全阀校验数据，可先登记安全阀",
  recordNoun: "安全阀校验记录",
  createHint: "安全阀登记入口尚未接入审批流",
  actionFail: "安全阀校验动作未生效，请稍后重试",
  listThrow: "安全阀列表读取失败",
  listFail: "安全阀校验操作失败"
  },
  {
  key: "gauge",
  title: "压力表检定管理",
  desc: "维护压力表，围绕压力表编号、所属设备、量程范围、精度等级做登记、筛选与状态流转。",
  fields: ["压力表编号", "所属设备", "量程范围", "精度等级", "检定日期", "下次检定日", "检定结论", "仪表状态"],
  actions: ["安排检定", "登记合格", "办理停用"],
  statuses: ["检定合格", "即将到期", "待检定", "已停用"],
  primaryText: "登记压力表",
  exportText: "导出压力表检定清单",
  emptyText: "暂无压力表检定数据，可先登记压力表",
  recordNoun: "压力表检定记录",
  createHint: "压力表登记入口尚未接入审批流",
  actionFail: "压力表检定动作未生效，请稍后重试",
  listThrow: "压力表列表读取失败",
  listFail: "压力表检定操作失败"
  },
  {
  key: "sparepart",
  title: "备件管理管理",
  desc: "维护备件，围绕备件编号、备件名称、规格型号、适用设备做登记、筛选与状态流转。",
  fields: ["备件编号", "备件名称", "规格型号", "适用设备", "存放位置", "最低保有量", "当前余量", "备件状态"],
  actions: ["办理领用", "采购入仓", "停用备件"],
  statuses: ["充足", "不足", "待采购", "已停用"],
  primaryText: "登记备件",
  exportText: "导出备件管理清单",
  emptyText: "暂无备件管理数据，可先登记备件",
  recordNoun: "备件管理记录",
  createHint: "备件登记入口尚未接入审批流",
  actionFail: "备件管理动作未生效，请稍后重试",
  listThrow: "备件列表读取失败",
  listFail: "备件管理操作失败"
  },
  {
  key: "emergency",
  title: "应急演练管理",
  desc: "维护演练记录，围绕演练编号、演练主题、演练类型、参与单位做登记、筛选与状态流转。",
  fields: ["演练编号", "演练主题", "演练类型", "参与单位", "演练日期", "演练评估", "改进措施", "演练状态"],
  actions: ["组织演练", "完成演练", "复盘总结"],
  statuses: ["待组织", "已组织", "已完成", "已复盘"],
  primaryText: "登记演练记录",
  exportText: "导出应急演练清单",
  emptyText: "暂无应急演练数据，可先登记演练记录",
  recordNoun: "应急演练记录",
  createHint: "演练记录登记入口尚未接入审批流",
  actionFail: "应急演练动作未生效，请稍后重试",
  listThrow: "演练记录列表读取失败",
  listFail: "应急演练操作失败"
  },
  {
  key: "energyeff",
  title: "能效监测管理",
  desc: "维护能效记录，围绕记录编号、设备类型、耗能量、单耗指标做登记、筛选与状态流转。",
  fields: ["记录编号", "设备类型", "耗能量", "单耗指标", "对标基准", "偏差比率", "记录月份", "能效状态"],
  actions: ["记录偏差", "分析原因", "调整优化"],
  statuses: ["达标", "轻微偏差", "显著偏差", "已调整"],
  primaryText: "登记能效记录",
  exportText: "导出能效监测清单",
  emptyText: "暂无能效监测数据，可先登记能效记录",
  recordNoun: "能效监测记录",
  createHint: "能效记录登记入口尚未接入审批流",
  actionFail: "能效监测动作未生效，请稍后重试",
  listThrow: "能效记录列表读取失败",
  listFail: "能效监测操作失败"
  },
  {
  key: "archive",
  title: "档案管理管理",
  desc: "维护设备档案，围绕档案编号、所属设备、档案类别、归档日期做登记、筛选与状态流转。",
  fields: ["档案编号", "所属设备", "档案类别", "归档日期", "借阅人", "借阅日期", "归还日期", "档案状态"],
  actions: ["办理借阅", "登记归还", "申请销毁"],
  statuses: ["在库", "借出中", "已归还", "已销毁"],
  primaryText: "登记设备档案",
  exportText: "导出档案管理清单",
  emptyText: "暂无档案管理数据，可先登记设备档案",
  recordNoun: "档案管理记录",
  createHint: "设备档案登记入口尚未接入审批流",
  actionFail: "档案管理动作未生效，请稍后重试",
  listThrow: "设备档案列表读取失败",
  listFail: "档案管理操作失败"
  },
  {
  key: "contract",
  title: "维保合同管理",
  desc: "维护维保合同，围绕合同编号、签约单位、维保范围、合同金额做登记、筛选与状态流转。",
  fields: ["合同编号", "签约单位", "维保范围", "合同金额", "签约日期", "到期日期", "是否续签", "合同状态"],
  actions: ["签订合同", "到期续签", "终止合同"],
  statuses: ["待签约", "执行中", "即将到期", "已终止"],
  primaryText: "登记维保合同",
  exportText: "导出维保合同清单",
  emptyText: "暂无维保合同数据，可先登记维保合同",
  recordNoun: "维保合同记录",
  createHint: "维保合同登记入口尚未接入审批流",
  actionFail: "维保合同动作未生效，请稍后重试",
  listThrow: "维保合同列表读取失败",
  listFail: "维保合同操作失败"
  },
]

export function moduleMeta(key: string): ModuleMeta {
  const found = MODULES.find((item) => item.key === key)
  if (!found) throw new Error(`未知模块 ${key}`)
  return found
}